CarWorkshop/Models/Ticket.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace CarWorkshop.Models
{
    public class Ticket
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Range(0, int.MaxValue)]
        public int Id { get; set; }

        [Required]
        public string? Brand { get; set; }
        [Required]
        public string? Model { get; set; }
        [Required]

        [Display(Name = "License Plate")]
        public string? RegistrationID { get; set; }
        [Required]
        public string? Description { get; set; }

        public string? EmployeeID { get; set; }

        [Display(Name = "Estimate Description")]
        public string? EstimateDescription { get; set; }
        [Range(0, float.MaxValue)]

        [Display(Name = "Estimate Cost ($)")]
        public float EstimateCost { get; set; }

        [Display(Name = "Accepted by client?")]
        public bool EstimateAcceptedByClient { get; set; }
        [Range(0, float.MaxValue)]

        [Display(Name = "Paid by client ($)")]
        public float PaidByClient { get; set; }

        public string? State { get; set; }
    }
}

CarWorkshop/ViewModels/DetailsViewModel.cs
using CarWorkshop.Models;

namespace CarWorkshop.ViewModels
{
    public class DetailsViewModel
    {
        
        public Ticket TicketData { get; set; }
        public WeeklySchedule TicketTimeTable { get; set; }
        public List<BoughtPart> PartsData { get; set; }

        public DateTime Date { get; set; }

        public DetailsViewModel(Ticket ticket, WeeklySchedule ticketSchedule, List<BoughtPart> parts, DateTime date)
        {
            TicketData = ticket;
            TicketTimeTable = ticketSchedule;
            PartsData = parts;
            Date = date;
        }

    }
}

CarWorkshop/ViewModels/EditViewModel.cs
using CarWorkshop.Models;

namespace CarWorkshop.ViewModels
{
    public class EditViewModel
    {
        public Ticket Ticket { get; set; }
        public List<BoughtPart> Parts { get; set; }
    }
}

CarWorkshop/Controllers/BoughtPartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CarWorkshop.Data;
using CarWorkshop.Models;
using Microsoft.AspNetCore.Identity;
using CarWorkshop.Areas.Identity.Data;
using System.Net.Sockets;

namespace CarWorkshop.Controllers
{
    public class BoughtPartsController : Controller
    {
        private readonly AuthDbContext _context;
        private readonly UserManager<User> _userManager;

        int ticketId;

        public BoughtPartsController(AuthDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: BoughtParts
        public async Task<IActionResult> Index(int Id) // id 0 means no ticket is selected
        {
            ticketId = Id;
            Console.WriteLine("Ticket ID: " + Id);
            List<BoughtPart> allParts = await _context.BoughtPart.ToListAsync();
            
            List<BoughtPart> ticketparts = allParts.Where(p => p.TicketId == Id).ToList();

            if(Id == 0)
            {
                return View(allParts);
            }
            else
            {
                return View(ticketparts);
            }   
        }

        // GET: BoughtParts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boughtPart = await _context.BoughtPart
                .FirstOrDefaultAsync(m => m.Id == id);
            if (boughtPart == null)
            {
                return NotFound();
            }

            return View(boughtPart);
        }

        // GET: BoughtParts/Create
        public IActionResult Create(int ticketID)
        {
            var ticket = _context.Ticket.Find(ticketID);
            if (ticket == null)
            {
                return NotFound();
            }
            var user = _userManager.FindByNameAsync(User.Identity.Name).Result;

            if(user == null)
            {
                return RedirectToAction("Index", "Home");
            }

            if (user.Id != ticket.EmployeeID)
            {
                return RedirectToAction("Index", "Home");
            }

            ViewBag.TicketId = ticketID;
            var boughtPart = new BoughtPart { TicketId = ticketID };
            return View(boughtPart);
        }

        // POST: BoughtParts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TicketId,Name,Amount,Price")] BoughtPart boughtPart)
        {
            
            if (ModelState.IsValid)
            {
                _context.Add(boughtPart);
                await _context.SaveChangesAsync();
                return RedirectToAction("Edit", "Tickets", new { id = boughtPart.TicketId });
            }
            return View(boughtPart);
        }

        // GET: BoughtParts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boughtPart = await _context.BoughtPart.FindAsync(id);
            if (boughtPart == null)
            {
                return NotFound();
            }
            return View(boughtPart);
        }

        // POST: BoughtParts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TicketId,Name,Amount,Price")] BoughtPart boughtPart)
        {
            if (id != boughtPart.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(boughtPart);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BoughtPartExists(boughtPart.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(boughtPart);
        }

        // GET: BoughtParts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boughtPart = await _context.BoughtPart
                .FirstOrDefaultAsync(m => m.Id == id);
            if (boughtPart == null)
            {
                return NotFound();
            }

            return View(boughtPart);
        }

        // POST: BoughtParts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var boughtPart = await _context.BoughtPart.FindAsync(id);
            if (boughtPart != null)
            {
                _context.BoughtPart.Remove(boughtPart);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BoughtPartExists(int id)
        {
            return _context.BoughtPart.Any(e => e.Id == id);
        }
    }
}

CarWorkshop/Controllers/TicketScheduleController.cs
using CarWorkshop.Areas.Identity.Data;
using CarWorkshop.Data;
using CarWorkshop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CarWorkshop.Controllers
{
    [Authorize(Roles = "Employee")]
    public class TicketScheduleController : Controller
    {
        private readonly AuthDbContext _context;
        private readonly UserManager<User> _userManager;
        public TicketScheduleController(AuthDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public IActionResult Index(int ticketID, DateTime? selectedDate)
        {

            var ticket = _context.Ticket.Find(ticketID);
            var user = _userManager.GetUserAsync(User).Result;

            if (ticket == null || user == null)
            {
                   return RedirectToAction("Index", "Home");
            }

            if (user.Id != ticket.EmployeeID)
            {
                return RedirectToAction("Index", "Home");
            }

            // If no date is selected, default to today's date
            DateTime currentDate = selectedDate ?? DateTime.Today;

            DateTime sunday = currentDate.AddDays(-(((int)currentDate.DayOfWeek + 7) % 7)); ;
            DateTime saturday;
    
            saturday = sunday.AddDays(6);
            
            saturday = saturday.Date;
            sunday = sunday.Date;


            // Generate the week table based on the start and end dates
            var model = GenerateWeekTable(user.Id, ticketID, sunday, saturday);
            model.Date = currentDate;

            return View(model);
        }

        private TicketSchedule GenerateWeekTable(string uID, int tID, DateTime startDate, DateTime endDate)
        {
            string userId = uID;
            int tickedID = tID;
            

            WeeklySchedule weekSchedule = new WeeklySchedule();

            for (DateTime date = startDate; date <= endDate; date = date.AddDays(1))
            {

                var timeSlots = GetTimeSlotsForDate(tID, date);


                switch (date.DayOfWeek)
                {
                    case DayOfWeek.Monday:
                        weekSchedule.Monday = timeSlots;
                        break;
                    case DayOfWeek.Tuesday:
                        weekSchedule.Tuesday = timeSlots;
                        break;
                    case DayOfWeek.Wednesday:
                        weekSchedule.Wednesday = timeSlots;
                        break;
                    case DayOfWeek.Thursday:
                        weekSchedule.Thursday = timeSlots;
                        break;
                    case DayOfWeek.Friday:
                        weekSchedule.Friday = timeSlots;
                        break;
                    case DayOfWeek.Saturday:
                        weekSchedule.Saturday = timeSlots;
                        break;
                    case DayOfWeek.Sunday:
                        weekSchedule.Sunday = timeSlots;
                        break;
                }
            }

            weekSchedule.Monday ??= new List<TimeSlot>();
            weekSchedule.Tuesday ??= new List<TimeSlot>();
            weekSchedule.Wednesday ??= new List<TimeSlot>();
            weekSchedule.Thursday ??= new List<TimeSlot>();
            weekSchedule.Friday ??= new List<TimeSlot>();
            weekSchedule.Saturday ??= new List<TimeSlot>();
            weekSchedule.Sunday ??= new List<TimeSlot>();

            var takenTimeSlots = _context.TimeSlot.Where(ts => ts.TicketID != tID && ts.TicketID != 0 && ts.EmployeeID == userId).ToList();

            var employeeScheduleSlots = _context.TimeSlot.Where(ts => (ts.TicketID == 0 && ts.EmployeeID == userId)).ToList();
           
            var ticketSchedule = new TicketSchedule
            {
                employeeID = userId,
                ticketID = tID,
                Date = startDate,
                takenTimeSlots = takenTimeSlots,
                employeeScheduleSlots = employeeScheduleSlots,
                WeeklySchedule = weekSchedule
            };

            return ticketSchedule;
        }

        private List<TimeSlot> GetTimeSlotsForDate(int ticketID, DateTime date)
        {
            List<TimeSlot> timeSlots = _context.TimeSlot.Where(ts => ts.TicketID == ticketID && ts.BeginTime.Date == date.Date).ToList();
            
            return timeSlots;
        }

        [HttpPost]
        public IActionResult AddSlot(int ticketID, int day, string time, DateTime selectedDate)
        {
            
            var user = _userManager.GetUserAsync(User).Result;
            string userId = user.Id;

            if (!TimeSpan.TryParse(time, out TimeSpan timeOfDay))
            {
                return BadRequest("Invalid time format");
            }

            
            DateTime sunday = selectedDate.AddDays(-(int)selectedDate.DayOfWeek);
       
            DateTime slotTime = sunday.AddDays(day).Add(timeOfDay); 
           

            // Check if the selected slot is already taken
            bool slotTaken = _context.TimeSlot.Any(ts => ts.TicketID != ticketID && ts.EmployeeID == userId && ts.TicketID != 0 && ts.BeginTime == slotTime);
            if (slotTaken)
            {
                return BadRequest("Slot is already taken");
            }


            TimeSlot newSlot = new TimeSlot
            {
                EmployeeID = userId,
                BeginTime = slotTime,
                TicketID = ticketID
            };


            _context.TimeSlot.Add(newSlot);
            _context.SaveChanges();


            return RedirectToAction("Index", new { ticketID, selectedDate});
        }


    

        public async Task<IActionResult> DeleteSlot(string id)
        {

            TimeSlot timeSlot = await _context.TimeSlot.FindAsync(id);

            DateTime selectedDate = timeSlot.BeginTime;
            int ticketID = timeSlot.TicketID;
            if (timeSlot != null)
            {
                _context.TimeSlot.Remove(timeSlot);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Index", new { ticketID, selectedDate});
        }
    }
}

CarWorkshop/Views/Tickets/Create.cshtml
@model CarWorkshop.Models.Ticket

@{
    ViewData["Title"] = "Create";
}

<h1>Create a ticket</h1>
<a asp-action="Index">Back to List</a>


<h4>Ticket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegistrationID" class="control-label"></label>
                <input asp-for="RegistrationID" class="form-control" />
                <span asp-validation-for="RegistrationID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>           
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarWorkshop/Views/Tickets/Delete.cshtml
@model CarWorkshop.Models.Ticket

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegistrationID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeeID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmployeeID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstimateDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstimateDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstimateCost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstimateCost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstimateAcceptedByClient)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstimateAcceptedByClient)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaidByClient)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaidByClient)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CarWorkshop/Views/Tickets/Details.cshtml
@model CarWorkshop.ViewModels.DetailsViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
@if (Model.TicketData.State != "Closed")
{
<div>
    <h4>Ticket timetable</h4>
    <a asp-action="EmployeeTickets" asp-controller="Tickets">Back to ticket list</a>
    @if (Model.TicketData.State != "Closed")
    {
        <a asp-action="Edit" asp-route-id="@Model.TicketData.Id">Edit the ticket</a>
    }
    <form asp-controller="Tickets" asp-action="Details" method="get">
        <label for="selectedDate">Select Date:</label>
        <input type="hidden" name="id" value="@Model.TicketData.Id">
        <input type="date" id="selectedDate" name="selectedDate" value="@(Model.Date.ToString("yyyy-MM-dd") ?? DateTime.Now.ToString("yyyy-MM-dd"))">
        <input type="submit" value="Submit">
    </form>
    <div>Displaying week for selected date - @Model.Date.ToString("yyyy-MM-dd") is @Model.Date.DayOfWeek</div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>Time</th>
            <th>Sunday</th>
            <th>Monday</th>
            <th>Tuesday</th>
            <th>Wednesday</th>
            <th>Thursday</th>
            <th>Friday</th>
            <th>Saturday</th>

        </tr>
    </thead>

    <tbody>
            
            @for (int hour = 9; hour <= 17; hour++)
            {
                <tr>
                    <td>@hour:00</td>
                    @for (int day = 0; day < 7; day++)
                    {
                        <td>
                        @{
                            var currentDay = Model.TicketTimeTable.GetDayByIndex(day);
                            var currentTimeSlot = currentDay?.FirstOrDefault(ts => ts.BeginTime.Hour == hour);
                            bool isTaken = false;
                            if (currentDay != null)
                            {
                                currentTimeSlot = currentDay?.FirstOrDefault(ts => ts.BeginTime.Hour == hour);
                                if (currentTimeSlot != null)
                                {
                                    isTaken = true;
                                }
                                else
                                {
                                    isTaken = false;
                                }
                            }

                        }

                        @if (isTaken)
                        {
                            <button type="button" class="btn btn-secondary" disabled style="background-color: blue;">Used</button>
                        }
                        else
                        {
                            <button type="button" class="btn btn-secondary" disabled>Not used</button>
                        }
                    </td>

                    }
                </tr>
            }
    </tbody>
</table>

}




<div>
    <h4>Ticket information</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TicketData.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TicketData.Brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TicketData.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TicketData.Model)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TicketData.RegistrationID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TicketData.RegistrationID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TicketData.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TicketData.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TicketData.EmployeeID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TicketData.EmployeeID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TicketData.EstimateDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TicketData.EstimateDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TicketData.EstimateCost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TicketData.EstimateCost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TicketData.EstimateAcceptedByClient)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TicketData.EstimateAcceptedByClient)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TicketData.PaidByClient)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TicketData.PaidByClient)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TicketData.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TicketData.State)
        </dd>
    </dl>
</div>

<table class="table">
    <thead>
        <h2>List of parts</h2>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PartsData[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PartsData[0].Amount)
            </th>
            <th>
                Price($)
            </th>
            <th>
                Total Price($)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.PartsData)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>

                <td>
                    @(item.Price * item.Amount)
                </td>
            </tr>
        }
    </tbody>
</table>

CarWorkshop/Views/Tickets/Edit.cshtml
@model CarWorkshop.ViewModels.EditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Ticket (ID: @Model.Ticket.Id)</h4>
<hr />
<a asp-action="EmployeeTickets" asp-controller="Tickets">Back to my tickets</a>

<div>
    <a asp-action="Index" asp-controller="TicketSchedule" asp-route-ticketID="@Model.Ticket.Id">Edit schedule</a>
</div>
@if(Model.Ticket.State == "Done")
{
    <div>
        <a asp-action="Close" asp-controller="Tickets" asp-route-id="@Model.Ticket.Id">Close ticket</a>
    </div>
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Ticket.Id" />
            <div class="form-group">
                <label asp-for="Ticket.Brand" class="control-label"></label>
                <input asp-for="Ticket.Brand" class="form-control" />
                <span asp-validation-for="Ticket.Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ticket.Model" class="control-label"></label>
                <input asp-for="Ticket.Model" class="form-control" />
                <span asp-validation-for="Ticket.Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ticket.RegistrationID" class="control-label"></label>
                <input asp-for="Ticket.RegistrationID" class="form-control" />
                <span asp-validation-for="Ticket.RegistrationID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ticket.Description" class="control-label"></label>
                <input asp-for="Ticket.Description" class="form-control" />
                <span asp-validation-for="Ticket.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ticket.EstimateDescription" class="control-label"></label>
                <input asp-for="Ticket.EstimateDescription" class="form-control" />
                <span asp-validation-for="Ticket.EstimateDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ticket.EstimateCost" class="control-label"></label>
                <input asp-for="Ticket.EstimateCost" class="form-control" />
                <span asp-validation-for="Ticket.EstimateCost" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ticket.EstimateAcceptedByClient" /> @Html.DisplayNameFor(model => model.Ticket.EstimateAcceptedByClient)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Ticket.PaidByClient" class="control-label"></label>
                <input asp-for="Ticket.PaidByClient" class="form-control" />
                <span asp-validation-for="Ticket.PaidByClient" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>    
        </form>
        
        <table class="table">
            <thead>
                <h2>List of parts</h2>
                <a asp-action="Create" asp-controller="BoughtParts" asp-route-ticketID="@Model.Ticket.Id">Add new part</a>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Parts[0].TicketId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Parts[0].Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Parts[0].Amount)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Parts[0].Price)
                    </th>
                    <th>
                        Total Price ($)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Parts)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.TicketId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Amount)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Price)
                        </td>
                            
                            <td>
                                @(item.Price * item.Amount)
                            </td>
                        
                        <td>
                            <a asp-action="DeletePart" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}